name: 'Quality Checks'
description: 'We are demo'
inputs:
  NODE_VERSION: # id of input
    description: 'Who to greet'
    required: true
    default: '22.0.0'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.NODE_VERSION }}
    - name: Install
      run: npm install
    - name: Unit Test
      run: npm run test
    - name: Lint
      run: npm run lint
