name: CI workflow

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run Lint
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.0.0

      - name: Check env
        run: echo ${{ vars.URLS }}
        shell: bash

      - name: Install
        run: npm install
        shell: bash

      - name: Unit Test
        run: npm run test
        shell: bash

      - name: Lint
        run: npm run lint
        shell: bash

  unit-test:
    strategy:
      fail-fast: false
      matrix:
        url: ${{ vars.ZAP_URLS }}
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Check env
        run: echo ${{ vars.URLS }}
        shell: bash
