name: CI workflow

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run Lint
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.0.0

      - name: Check env
        run: echo ${{ vars.URLS }}
        shell: bash

      - name: Install
        run: npm install
        shell: bash

      - name: Unit Test
        run: npm run test
        shell: bash

      - name: Lint
        run: npm run lint
        shell: bash


  parse-matrix:
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      urls: ${{ steps.set-urls.outputs.urls }}
    steps:
      - name: Set URLs
        id: set-urls
        shell: bash
        run: |
          echo "urls=${{ vars.URLS }}" >> "$GITHUB_OUTPUT"
          echo $GITHUB_OUTPUT

  unit-test:
    needs: parse-matrix
    strategy:
      matrix:
        url: ${{ fromJSON(needs.parse-matrix.outputs.urls) }}
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Check env
        run: echo ${{ vars.URLS }}
        shell: bash
